### PR TITLE
IDA 9 support

### PR DESCRIPTION
**Pull request by vnescape**

### CODE REVIEW

**Comment by haiyuidesu** [comment]
Hello,

Thank you for your time and energy spent on this update, I appreciate it a lot!

However, it seems that I got the following error on IDA `7.0`

```
prologue_bytes = bytes.fromhex(prologue.replace(" ", ""))
AttributeError: type object 'str' has no attribute 'fromhex'
```

I don't know if it comes from this version that seems to be pretty old by now, but I'm not owning any copy of IDA 9 that would allow me to find a fix that would work for every versions possible.

Could you try to fix this issue? :)

**Comment by vnescape** [comment]
Hi,

Can you give me details of the IDA version you're using and the binary you're trying to analyse? Just to make it easier to test for this bug.

Thanks for letting me know about this bug.

**Comment by haiyuidesu** [comment]
Hello again,

As mentioned in the first comment, I've been using IDA `7.0` on macOS with an [M9 B0/B1 SEPROM](https://securerom.fun/resources/SEPROM/AppleSEPROM-M9-B0-B1).

I don't think that the choice of the ROM really matters there but more the IDA version (as it still uses [Python 2.7](https://www.python.org/ftp/python/2.7.18/python-2.7.18-macosx10.9.pkg)), which makes things a little bit trickier as you've got to deal with code that would run fine on both versions), but there you go.

Thank you for your time :)

**Comment by vnescape** [comment]
I've updated the code to work with IDA 7.0 now. Not sure if ida_search.find_binary() is deprecated in IDA 9.0 or earlier

**Comment by haiyuidesu** [comment]
Yup, this is working fine!

Thank you once again :)
